{
  "openapi": "3.0.1",
  "info": {
    "title": "心知天气API",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/v3/weather/now.json": {
      "get": {
        "summary": "天气实况",
        "operationId": "seniverse_current_weather",
        "deprecated": false,
        "description": "获取指定城市的天气实况。",
        "tags": [],
        "parameters": [{
          "name": "key",
          "in": "query",
          "description": "你的 API 密钥",
          "required": false,
          "example": "",
          "schema": {
            "type": "string"
          }
        }, {
          "name": "location",
          "in": "query",
          "description": "所查询的位置",
          "required": false,
          "example": "北京",
          "schema": {
            "type": "string"
          }
        }, {
          "name": "language",
          "in": "query",
          "description": "语言",
          "required": false,
          "example": "zh-Hans",
          "schema": {
            "type": "string"
          }
        }, {
          "name": "unit",
          "in": "query",
          "description": "单位",
          "required": false,
          "example": "c",
          "schema": {
            "type": "string"
          }
        }],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "results": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "location": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "string"
                              },
                              "name": {
                                "type": "string"
                              },
                              "country": {
                                "type": "string"
                              },
                              "path": {
                                "type": "string"
                              },
                              "timezone": {
                                "type": "string"
                              },
                              "timezone_offset": {
                                "type": "string"
                              }
                            },
                            "required": ["id", "name", "country", "path", "timezone", "timezone_offset"]
                          },
                          "now": {
                            "type": "object",
                            "properties": {
                              "text": {
                                "description": "天气现象文字",
                                "type": "string"
                              },
                              "code": {
                                "description": "天气现象代码",
                                "type": "string"
                              },
                              "temperature": {
                                "description": "温度，单位为c摄氏度或f华氏度",
                                "type": "string"
                              }
                            },
                            "required": ["text", "code", "temperature"]
                          },
                          "last_update": {
                            "description": "数据更新时间（该城市的本地时间）",
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "required": ["results"]
                },
                "example": {
                  "results": [{
                    "location": {
                      "id": "C23NB62W20TF",
                      "name": "西雅图",
                      "country": "US",
                      "path": "西雅图,华盛顿州,美国",
                      "timezone": "America/Los_Angeles",
                      "timezone_offset": "-07:00"
                    },
                    "now": {
                      "text": "多云",
                      "code": "4",
                      "temperature": "14"
                    },
                    "last_update": "2015-09-25T22:45:00-07:00"
                  }]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/v3/weather/daily.json": {
      "get": {
        "summary": "逐日天气预报",
        "operationId": "seniverse_day_to_day_weather",
        "deprecated": false,
        "description": "获取指定城市未来最多 3天每天的白天和夜间预报天气。",
        "tags": [],
        "parameters": [{
          "name": "key",
          "in": "query",
          "description": "你的 API 密钥",
          "required": true,
          "example": "",
          "schema": {
            "type": "string"
          }
        }, {
          "name": "location",
          "in": "query",
          "description": "所查询的位置",
          "required": true,
          "example": "北京",
          "schema": {
            "type": "string"
          }
        }, {
          "name": "language",
          "in": "query",
          "description": "语言",
          "required": false,
          "example": "zh-Hans",
          "schema": {
            "type": "string"
          }
        }, {
          "name": "unit",
          "in": "query",
          "description": "单位",
          "required": false,
          "example": "c",
          "schema": {
            "type": "string"
          }
        }, {
          "name": "start",
          "in": "query",
          "description": "起始时间",
          "required": false,
          "example": "0",
          "schema": {
            "type": "string"
          }
        }, {
          "name": "days",
          "in": "query",
          "description": "天数",
          "required": false,
          "example": "5",
          "schema": {
            "type": "string"
          }
        }],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "results": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "location": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "string"
                              },
                              "name": {
                                "type": "string"
                              },
                              "country": {
                                "type": "string"
                              },
                              "path": {
                                "type": "string"
                              },
                              "timezone": {
                                "type": "string"
                              },
                              "timezone_offset": {
                                "type": "string"
                              }
                            },
                            "required": ["id", "name", "country", "path", "timezone", "timezone_offset"]
                          },
                          "daily": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "properties": {
                                "date": {
                                  "description": "日期（该城市的本地时间）",
                                  "type": "string"
                                },
                                "text_day": {
                                  "description": "白天天气现象文字",
                                  "type": "string"
                                },
                                "code_day": {
                                  "description": "白天天气现象代码",
                                  "type": "string"
                                },
                                "text_night": {
                                  "description": "晚间天气现象文字",
                                  "type": "string"
                                },
                                "code_night": {
                                  "description": "晚间天气现象代码",
                                  "type": "string"
                                },
                                "high": {
                                  "description": "当天最高温度",
                                  "type": "string"
                                },
                                "low": {
                                  "description": "当天最低温度",
                                  "type": "string"
                                },
                                "precip": {
                                  "description": "降水概率，范围0~1，单位百分比（目前仅支持国内城市）",
                                  "type": "string"
                                },
                                "wind_direction": {
                                  "description": "风向文字",
                                  "type": "string"
                                },
                                "wind_direction_degree": {
                                  "description": "风向角度，范围0~360",
                                  "type": "string"
                                },
                                "wind_speed": {
                                  "description": "风速，单位km/h（当unit=c时）、mph（当unit=f时）",
                                  "type": "string"
                                },
                                "wind_scale": {
                                  "description": "风力等级",
                                  "type": "string"
                                },
                                "rainfall": {
                                  "description": "降水量，单位mm（目前仅支持国内城市）",
                                  "type": "string"
                                },
                                "humidity": {
                                  "description": "相对湿度，0~100，单位为百分比",
                                  "type": "string"
                                }
                              },
                              "required": ["date", "text_day", "code_day", "text_night", "code_night", "high", "low", "precip", "wind_direction", "wind_direction_degree", "wind_speed", "wind_scale", "rainfall", "humidity"]
                            },
                            "description": "返回指定days天数的结果"
                          },
                          "last_update": {
                            "description": "数据更新时间（该城市的本地时间）",
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "required": ["results"]
                },
                "example": {
                  "results": [{
                    "location": {
                      "id": "WX4FBXXFKE4F",
                      "name": "北京",
                      "country": "CN",
                      "path": "北京,北京,中国",
                      "timezone": "Asia/Shanghai",
                      "timezone_offset": "+08:00"
                    },
                    "daily": [{
                      "date": "2015-09-20",
                      "text_day": "多云",
                      "code_day": "4",
                      "text_night": "晴",
                      "code_night": "0",
                      "high": "26",
                      "low": "17",
                      "precip": "0",
                      "wind_direction": "",
                      "wind_direction_degree": "255",
                      "wind_speed": "9.66",
                      "wind_scale": "",
                      "rainfall": "0.0",
                      "humidity": "76"
                    }, {
                      "date": "2015-09-21",
                      "text_day": "晴",
                      "code_day": "0",
                      "text_night": "晴",
                      "code_night": "0",
                      "high": "27",
                      "low": "17",
                      "precip": "0",
                      "wind_direction": "",
                      "wind_direction_degree": "157",
                      "wind_speed": "17.7",
                      "wind_scale": "3",
                      "rainfall": "0.0",
                      "humidity": "76"
                    }],
                    "last_update": "2015-09-20T18:00:00+08:00"
                  }]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/v3/life/suggestion.json": {
      "get": {
        "summary": "生活指数",
        "operationId": "seniverse_life_index",
        "deprecated": false,
        "description": "获取指定城市的基本、交通、生活、运动、健康 5 大类共 27 项生活指数，预测至未来5天，仅支持中国城市。\n免费用户只返回 6 项基本类生活指数，且只有 brief，没有 details。\n● 基本类：穿衣、紫外线强度、洗车、旅游、感冒、运动\n● 交通类：交通、路况\n● 生活类：晾晒、雨伞、空调开启、啤酒、逛街、夜生活、约会\n● 运动类：晨练、钓鱼、划船、放风筝\n● 健康类：过敏、美发、化妆、风寒、防晒、空气污染扩散条件、舒适度、心情",
        "tags": [],
        "parameters": [{
          "name": "key",
          "in": "query",
          "description": "你的 API 密钥",
          "required": true,
          "example": "",
          "schema": {
            "type": "string"
          }
        }, {
          "name": "location",
          "in": "query",
          "description": "所查询的位置",
          "required": true,
          "example": "上海",
          "schema": {
            "type": "string"
          }
        }, {
          "name": "language",
          "in": "query",
          "description": "语言",
          "required": false,
          "example": "zh-Hans",
          "schema": {
            "type": "string"
          }
        }, {
          "name": "days",
          "in": "query",
          "description": "天数",
          "required": false,
          "example": "5",
          "schema": {
            "type": "string"
          }
        }],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "results": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "location": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "string"
                              },
                              "name": {
                                "type": "string"
                              },
                              "country": {
                                "type": "string"
                              },
                              "path": {
                                "type": "string"
                              },
                              "timezone": {
                                "type": "string"
                              },
                              "timezone_offset": {
                                "type": "string"
                              }
                            },
                            "required": ["id", "name", "country", "path", "timezone", "timezone_offset"]
                          },
                          "suggestion": {
                            "type": "object",
                            "properties": {
                              "ac": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "description": "简要建议",
                                    "type": "string"
                                  },
                                  "details": {
                                    "description": "详细建议",
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "air_pollution": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "airing": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "allergy": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "beer": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "boating": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "car_washing": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "comfort": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "dressing": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "fishing": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "flu": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "kiteflying": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "makeup": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "mood": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "morning_sport": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "road_condition": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "shopping": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "sport": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "sunscreen": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "traffic": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "umbrella": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              },
                              "uv": {
                                "type": "object",
                                "properties": {
                                  "brief": {
                                    "type": "string"
                                  },
                                  "details": {
                                    "type": "string"
                                  }
                                },
                                "required": ["brief", "details"]
                              }
                            },
                            "required": ["ac", "air_pollution", "airing", "allergy", "beer", "boating", "car_washing", "comfort", "dressing", "fishing", "flu", "kiteflying", "makeup", "mood", "morning_sport", "road_condition", "shopping", "sport", "sunscreen", "traffic", "umbrella", "uv"]
                          },
                          "last_update": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "required": ["results"]
                },
                "example": {
                  "results": [{
                    "location": {
                      "id": "WTW3SJ5ZBJUY",
                      "name": "上海",
                      "country": "CN",
                      "path": "上海,上海,中国",
                      "timezone": "Asia/Shanghai",
                      "timezone_offset": "+08:00"
                    },
                    "suggestion": {
                      "ac": {
                        "brief": "较少开启",
                        "details": "您将感到很舒适，一般不需要开启空调。"
                      },
                      "air_pollution": {
                        "brief": "较差",
                        "details": "气象条件较不利于空气污染物稀释、扩散和清除，请适当减少室外活动时间。"
                      },
                      "airing": {
                        "brief": "不太适宜",
                        "details": "天气阴沉，不利于水分的迅速蒸发，不太适宜晾晒。若需要晾晒，请尽量选择通风的地点。"
                      },
                      "allergy": {
                        "brief": "极不易发",
                        "details": "天气条件极不易诱发过敏，可放心外出，享受生活。"
                      },
                      "beer": {
                        "brief": "较不适宜",
                        "details": "您将会感到有些凉意，建议饮用常温啤酒，并少量饮用为好。"
                      },
                      "boating": {
                        "brief": "较适宜",
                        "details": "白天较适宜划船，但天气阴沉，气温稍低，请注意加衣，小心着凉。"
                      },
                      "car_washing": {
                        "brief": "不宜",
                        "details": "不宜洗车，未来24小时内有雨，如果在此期间洗车，雨水和路上的泥水可能会再次弄脏您的爱车。"
                      },
                      "chill": {
                        "brief": "凉",
                        "details": "感觉有点凉，室外活动注意适当增减衣物。"
                      },
                      "comfort": {
                        "brief": "较舒适",
                        "details": "白天天气阴沉，会感到有点儿凉，但大部分人完全可以接受。"
                      },
                      "dating": {
                        "brief": "较适宜",
                        "details": "虽然天空有些阴沉，但情侣们可以放心外出，不用担心天气来调皮捣乱而影响了兴致。"
                      },
                      "dressing": {
                        "brief": "较冷",
                        "details": "建议着厚外套加毛衣等服装。年老体弱者宜着大衣、呢外套加羊毛衫。"
                      },
                      "fishing": {
                        "brief": "较适宜",
                        "details": "较适合垂钓，但天气稍凉，会对垂钓产生一定的影响。"
                      },
                      "flu": {
                        "brief": "较易发",
                        "details": "天气较凉，较易发生感冒，请适当增加衣服。体质较弱的朋友尤其应该注意防护。"
                      },
                      "hair_dressing": {
                        "brief": "一般",
                        "details": "注意防晒，洗发不宜太勤，建议选用保湿防晒型洗发护发品。出门请戴上遮阳帽或打遮阳伞。"
                      },
                      "kiteflying": {
                        "brief": "不宜",
                        "details": "天气不好，不适宜放风筝。"
                      },
                      "makeup": {
                        "brief": "保湿",
                        "details": "皮肤易缺水，用润唇膏后再抹口红，用保湿型霜类化妆品。"
                      },
                      "mood": {
                        "brief": "较差",
                        "details": "天气阴沉，会感觉莫名的压抑，情绪低落，此时将所有的悲喜都静静地沉到心底，在喧嚣的尘世里，感受片刻恬淡的宁静。"
                      },
                      "morning_sport": {
                        "brief": "不宜",
                        "details": "阴天，早晨天气寒冷，请尽量避免户外晨练，若坚持室外晨练请注意保暖防冻，建议年老体弱人群适当减少晨练时间。"
                      },
                      "night_life": {
                        "brief": "较不适宜",
                        "details": "有降水，会给您的出行带来很大的不便，建议就近或最好在室内进行夜生活。"
                      },
                      "road_condition": {
                        "brief": "干燥",
                        "details": "阴天，路面比较干燥，路况较好。"
                      },
                      "shopping": {
                        "brief": "适宜",
                        "details": "阴天，在这种天气里去逛街，省去了涂防晒霜，打遮阳伞的麻烦，既可放松身心，又会有很多意外收获。"
                      },
                      "sport": {
                        "brief": "较适宜",
                        "details": "阴天，较适宜进行各种户内外运动。"
                      },
                      "sunscreen": {
                        "brief": "弱",
                        "details": "属弱紫外辐射天气，长期在户外，建议涂擦SPF在8-12之间的防晒护肤品。"
                      },
                      "traffic": {
                        "brief": "良好",
                        "details": "阴天，路面干燥，交通气象条件良好，车辆可以正常行驶。"
                      },
                      "travel": {
                        "brief": "适宜",
                        "details": "天气较好，温度适宜，总体来说还是好天气哦，这样的天气适宜旅游，您可以尽情地享受大自然的风光。"
                      },
                      "umbrella": {
                        "brief": "不带伞",
                        "details": "阴天，但降水概率很低，因此您在出门的时候无须带雨伞。"
                      },
                      "uv": {
                        "brief": "最弱",
                        "details": "属弱紫外线辐射天气，无需特别防护。若长期在户外，建议涂擦SPF在8-12之间的防晒护肤品。"
                      }
                    },
                    "last_update": "2015-11-28T14:10:48+08:00"
                  }]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/v3/location/search.json": {
      "get": {
        "summary": "城市搜索",
        "operationId": "seniverse_city_search",
        "deprecated": false,
        "description": "根据城市ID、中文、英文、拼音、IP、经纬度搜索匹配的城市。\n请求地址示例\n● 用城市ID搜索 https://api.seniverse.com/v3/location/search.json?key=your_api_key&q=WX4FBXXFKE4F\n● 用城市中文搜索 https://api.seniverse.com/v3/location/search.json?key=your_api_key&q=北京\n● 用城市英文搜索 https://api.seniverse.com/v3/location/search.json?key=your_api_key&q=beijing\n● 用城市拼音缩写搜索 https://api.seniverse.com/v3/location/search.json?key=your_api_key&q=bj\n● 用IP地址搜索 https://api.seniverse.com/v3/location/search.json?key=your_api_key&q=220.181.111.86\n● 用经纬度搜索 https://api.seniverse.com/v3/location/search.json?key=your_api_key&q=39.93:116.40\n● 用省市名称限定搜索 https://api.seniverse.com/v3/location/search.json?key=your_api_key&q=辽宁朝阳\n● 搜索所有中英文名称中包含“san”的城市，返回第2页的10个结果 https://api.seniverse.com/v3/location/search.json?key=your_api_key&q=san&limit=10&offset=10",
        "tags": [],
        "parameters": [{
          "name": "key",
          "in": "query",
          "description": "你的API密钥",
          "required": true,
          "example": "",
          "schema": {
            "type": "string"
          }
        }, {
          "name": "q",
          "in": "query",
          "description": "所查询的位置",
          "required": true,
          "example": ["北京"],
          "schema": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }, {
          "name": "limit",
          "in": "query",
          "description": "分页每页最多记录数",
          "required": false,
          "example": "10",
          "schema": {
            "type": "string"
          }
        }, {
          "name": "offset",
          "in": "query",
          "description": "跳过的记录数 (可选) 配合limit参数实现分页",
          "required": false,
          "example": "0",
          "schema": {
            "type": "string"
          }
        }],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "results": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "country": {
                            "type": "string"
                          },
                          "path": {
                            "type": "string"
                          },
                          "timezone": {
                            "type": "string"
                          },
                          "timezone_offset": {
                            "type": "string"
                          }
                        },
                        "required": ["id", "name", "country", "path", "timezone", "timezone_offset"]
                      }
                    }
                  },
                  "required": ["results"]
                },
                "example": {
                  "results": [{
                    "id": "WXMSKZT4B3TT",
                    "name": "朝阳",
                    "country": "CN",
                    "path": "朝阳,朝阳,辽宁,中国",
                    "timezone": "Asia/Shanghai",
                    "timezone_offset": "+08:00"
                  }, {
                    "id": "UZVXBZYXCZUZ",
                    "name": "朝阳县",
                    "country": "CN",
                    "path": "朝阳县,朝阳,辽宁,中国",
                    "timezone": "Asia/Shanghai",
                    "timezone_offset": "+08:00"
                  }]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {}
  },
  "servers": [{
    "url": "https://api.seniverse.com",
    "description": "心知天气url"
  }]
}